name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - uses: joschi/setup-jdk@v1
      with:
        java-version: 'openjdk11'
        architecture: 'x64'
    - name: Build with Gradle
      run: ./gradlew build
